# Generated by Django 3.0.7 on 2020-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=128)),
                ('followed', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Follow',
            },
        ),
        migrations.CreateModel(
            name='SecureUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('point', models.IntegerField()),
            ],
            options={
                'db_table': 'SecureUser',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('point', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
