# Generated by Django 3.0.7 on 2020-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureuser',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
