# Generated by Django 3.0.7 on 2020-06-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_api', '0003_user_rtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=128)),
                ('longitude', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'GPS',
            },
        ),
    ]
